# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Freezed factory constructor params commonly trigger this.
    invalid_annotation_target: ignore

linter:
  rules:
    constant_identifier_names: false
